"""new fields in user model

Revision ID: 25764f9aa672
Revises: 2e107cdd0ba6
Create Date: 2026-08-09 17:42:18.937831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25764f9aa672'
down_revision = '2e107cdd0ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
